version: '3.6'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  postgres:
    image: bitnami/postgresql
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis
    